#!/bin/bash

USER_UID=$(id -u)
USER_GID=$(id -g)
BASE_DIR=$(dirname "$0")

if [ "$USER_UID" == "0" ]; then
  echo "Not to be run as root"
  exit 1
fi

sudo docker build -t rails-specific-vuejs-dev \
                     --build-arg USER_UID="$USER_UID" \
                     --build-arg USER_GID="$USER_GID" \
                     "$BASE_DIR"
