#!/bin/bash

USER_UID=$(id -u)
USER_GID=$(id -g)
BASE_DIR=$(dirname "$0")

if [ "$USER_UID" == "0" ]; then
  echo "Not to be run as root"
  exit 1
fi

PREFIX=
if ! docker ps > /dev/null 2>&1; then
  PREFIX=sudo
fi

"$PREFIX" docker build -t rails-specific-react-dev \
                       --build-arg USER_UID="$USER_UID" \
                       --build-arg USER_GID="$USER_GID" \
                       "$BASE_DIR"
