#!/bin/sh

LOCAL_PORT=3000
BASE_DIR=$(dirname "$0")

docker run -ti \
           --rm \
           -v "$(readlink -f "$BASE_DIR"):/opt/service/" \
           -p "$LOCAL_PORT:3000" \
           rails-specific-vuejs-dev
